// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using agenciaViajes.Application.Infrastructure.Context;

#nullable disable

namespace agenciaViajes.Application.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526193300_AddPaymentsFolioNumberSequence")]
    partial class AddPaymentsFolioNumberSequence
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally minimal: runtime uses Up/Down in the main migration class.
        }
    }
}
